version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: $DB_HOST
            port: $DB_PORT
            database: $DB_NAME
            user: $DB_USER
            password: $DB_PASS
            migrations: true
            rawAccess: true
            ssl: true
